MODEL_NAME = "unsloth/Qwen3-VL-8B-Instruct-unsloth-bnb-4bit"
MAX_SEQ_LEN = 16384
LORA_RANK = 16

DATASET = "HuggingFaceM4/ChartQA"
DATASET_SIZE = 500

REASONING_START = "<REASONING>"
REASONING_END = "</REASONING>"
SOLUTION_START = "<SOLUTION>"
SOLUTION_END = "</SOLUTION>"

# SFT
SFT_LEARNING_RATE = 2e-4
SFT_EPOCHS = 2
SFT_BATCH_SIZE = 2
SFT_GRAD_ACCUM_STEPS = 4
SFT_MAX_SEQ_LEN = 2048

# GRPO
GRPO_LEARNING_RATE = 5e-6
GRPO_EPOCHS = 1
GRPO_BATCH_SIZE = 4
GRPO_GRAD_ACCUM_STEPS = 1
GRPO_NUM_GENERATIONS = 4
